   # # Überschriften
    "Ü1" => "title",
    "Überschrift1" => "title",
    "titel" => "title",
    "Ü2" => "part",
    "Überschrift2" => "part",
    "teil" => "part",
    "kapitel" => "chapter",
    "Ü3" => "section",
    "Überschrift3" => "section",
    "abschnitt" => "section",
    "Ü4" => "subsection",
    "Überschrift4" => "subsection",
    "unterabschnitt" => "subsection",
    "Ü5" => "subsubsection",
    "Überschrift5" => "subsubsection",
    "subsubsection" => "subsubsection",
    "Ü6" => "paragraph",
    "Überschrift6" => "paragraph",
    "absatz" => "paragraph",
    "Ü" => "addsec",
    "Überschrift" => "addsec",
    # Anmerkungen
    "anmerkung" => "marginpar",


